version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:1.0.4
    ports:
      - "4566:4566" # LocalStack Gateway
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    # networks:
    #   - treinament-aws

  app:
    build: .
    container_name: "tooling"
    volumes:
      - .:/src
      - nodemodules:/src/node_modules
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - localstack
    environment:
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    # networks:
    #   - treinament-aws

  test:
    build: .
    container_name: "tooling-test"
    command: npm run test:watch
    volumes:
      - .:/src
      - nodemodules:/src/node_modules
    restart: on-failure
    depends_on:
      - localstack
    environment:
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    # networks:
    #   - treinament-aws

volumes:
  nodemodules: {}
# networks:
#   treinament-aws:
#     driver: bridge
